# Generated by Django 2.2 on 2019-04-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='share_poi',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='floor',
            field=models.IntegerField(default=1),
        ),
    ]
