# Generated by Django 2.2 on 2019-04-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_personiplink'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='location',
            name='lng',
            field=models.FloatField(default=0.0),
        ),
    ]
